name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  stylua:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/

  luacheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: sudo apt-get install -y luarocks && sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck lua/
